columns: 80
steps:
  - unicode_syntax:      { add_language_pragma: false }
  - imports:             { align: global }
  - language_pragmas:    { remove_redundant: true, style: vertical }
  - tabs:                { spaces: 4 }
  - records:             {}
  - trailing_whitespace: {}
language_extensions:
  - UnicodeSyntax